### ISSUE TITLE
Add the ACC_SYNTHETIC marker on generated code (to assist code coverage / Jacoco etc)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-agent#112]
If we add ACC_SYNTHETIC marker to generated methods and fields then these can be appropriately filtered out by code coverage tools like Jacoco.

----
Hi,
I just replaced Hibernate with Ebean with much success in our mixed Kotlin/Java Project and am currently using the Maven tile for bytecode Enhancement.
I noticed that the Jacoco report we use for Sonarqube inspection has several issues with recognizing test coverage in enhanced classes.
As the LineNumberTable seems to be intact, at first glance the enhanced bytecode doesn't seem to be marked as synthetic. Is there a reason for this?
Without any recognizable property, Jacoco won't be able to filter out those methods and fields [1] and mark the corresponding LineNumberTable lines.
Cheers, Miguel

[1]: https://github.com/jacoco/jacoco/wiki/FilteringOptions

**Comment by Iggle** [comment]
Hey Rob,
sorry for the delay. I've been having a look at this and so far I can mark most methods and fields as synthetic. I'm still not sure about the clinit method from the Entity enhancement, as this method is usually explicitly excluded from the synthetic specification:

> The only exceptions to this requirement are compiler-generated methods which are not considered implementation artifacts, namely the instance initialization method representing a default constructor of the Java programming language (§2.9), the class initialization method (§2.9), and the Enum.values() and Enum.valueOf() methods.

The label with the LineNumber declaration that is prepended to the method is for debugging information only, as far as I can see. Does this have a purpose or could I just remove that Label together with the linenumber?

With regards to Querybean enhancement, no methods are synthetically created, rather the already existing constructor is modified. I'm wondering wether the same label removal should be applied or if this should bother me at all, as Querybeans are generated code and therefore usually not present in code coverage reports.
Cheers, Miguel

**Comment by rbygrave** [comment]
Cool.

>  I'm still not sure about the clinit method

Yeah, I'm not sure about that either.

> The label with the LineNumber declaration that is prepended to the method is for debugging information only

Yes it is for debug only. The line number has been useful in that when we use IDE debug and step the IDE can go to the line and hence we know where we are in the generated code.  I'm not sure about losing the labels and line numbers.

I'd be keen to just stick to the ACC_SYNTHETIC for this change.

Cheers, Rob.

**Comment by rbygrave** [comment]
Closed as fixed with #113
