### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [ebean-orm/ebean-agent#117]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/io/ebean/enhance/asm/commons/SerialVersionUIDAdder.java: Line number => 436: API name => MessageDigest:First parameter (with value "SHA") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/io/ebean/enhance/asm/commons/SerialVersionUIDAdder.java: Line number => 436: API name => MessageDigest:<BR> File name => src/main/java/io/ebean/enhance/asm/commons/SerialVersionUIDAdder.java: Line number => 436: API name => MessageDigest:<BR>

**Comment by rbygrave** [comment]
Fixed, removed.
