### ISSUE TITLE
Please check master branch

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean-agent#179]
@rbygrave for a while, you gave me write permissions to your repositories.
Today I accidently pushed some changes to your master branch in this repository. (https://github.com/ebean-orm/ebean-agent/commit/cd2af57c1259d8246b1be6931467edaecb3567e2)

I reseted the branch to your last commit. Would you please check if everything is correct now.
I also dropped the permission to write to your repositories, so that this would not happen again.
(I think it is enough to create pull requests, as we did this in the past)

There is still a tag `ebean-agent-13.2.1-FOC1` which I cannot delete

cheers
Roland

**Comment by rbygrave** [comment]
Ha ha, I think we have all done an accidental push to master :)

master branch all looks good !!

**Comment by rbygrave** [comment]
I'll close this.
