### ISSUE TITLE
Enhancement does not correctly alter class signature

### ISSUE THREAD

**Issue by GithubUser8080** [ebean-orm/ebean-agent#206]
We noticed our app had some issues with the newer proguard, as generic type information is removed from classes after obfuscation. It looks like this [is partially because of using ebean ](https://github.com/Guardsquare/proguard/issues/396#issuecomment-2049519300). 

Reading the resulting bytecode of an ebean enhanced class myself, it looks like the implemented EntityBean interface is not present in the signature, and that is why IDEs also don't show it when opening the .class file. Would it be possibly to add "implements EntityBean" to signatures of enhanced classes? Thank you

**Comment by GithubUser8080** [comment]
Thank you for looking into this. I would like to ask if this is planned to be ported to 15.x too. Ebean 15.3.0 uses ebean agent 15.3.0 which does not seem to include this change.

**Comment by rbygrave** [comment]
> ebean agent 15.3.0 which does not seem to include this change.

15.3.0 does include this change. I've confirmed it - ClassAdpaterEntity making the call to VisitUtil.signatureAppend() etc.

**Comment by GithubUser8080** [comment]
> > ebean agent 15.3.0 which does not seem to include this change.
> 
> 15.3.0 does include this change. I've confirmed it - ClassAdpaterEntity making the call to VisitUtil.signatureAppend() etc.

Apologies, it was an error with sbt getting the wrong version. Thanks again
