### ISSUE TITLE
Enhancer prints to console

### ISSUE THREAD

**Issue by bergvandenp** [ebean-orm/ebean-agent#38]
I would like to be able to suppress the large amount of system printlns to the console. For me it's useless information during a maven build

The printing is done in EnhanceContext.java. I would suggest using the logger, but I suppose there's a reason for doing it this way?

**Comment by rbygrave** [comment]
You can use debug=0 as an argument ... and you'll get no logging. 

> but I suppose there's a reason for doing it this way?

Well, the logging ought to be used relatively rarely - it's not "application logging" per say.  It also is expected to run as an agent.

Could there be improvements to the logging (when used in each case of: javaagent / maven plugin / IDE plugin) - probably yes.  Generally though you can set it to debug=0 ... and just increase that when you really want to investigate what the enhancement is doing.

**Comment by rbygrave** [comment]
I'll close this for now.
