### ISSUE TITLE
Don't print Query Beans warning if Query Beans not used

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean-agent#46]
To avoid users misunderstanding, it would be nice to don't show the following warning message if Query Beans is not used on the project who just use "basic" querying system of Ebean .

```
---------------------------------------------------------------------------------------------
QueryBean Agent: No packages containing query beans - Missing ebean.mf files? this won't work.
---------------------------------------------------------------------------------------------
```

**Comment by rbygrave** [comment]
Yes, very good point.  Now that the one agent does both ... this needs to change.
