### ISSUE TITLE
MappedSuperclass with persistent fields intermittently gives error "bean is not abstract and does not override abstract method _ebean_intercept() in com.avaje.ebean.bean.EntityBean"

### ISSUE THREAD

**Issue by jokester01au** [ebean-orm/ebean-agent#49]
[error] src/models/main/java/models/SupplierStaff.java:31: models.SupplierStaff is not abstract and does not override abstract method _ebean_intercept() in com.avaje.ebean.bean.EntityBean
[error] public class SupplierStaff extends Staff implements Orderable {
[error] src/models/main/java/models/WorkArea.java:21: models.WorkArea is not abstract and does not override abstract method _ebean_intercept() in com.avaje.ebean.bean.EntityBean
[error] public class WorkArea extends AbstractStaffHolder implements Notifiable, Inheritable<WorkArea, Supplier>, ApiObject {

This happens intermittently to all of the models that I have that have MappedSuperclasses. (Staff and AbstractStaffHolder in the above are both MappedSuperclasses). 

If I delete the class file for SupplierStaff or for WorkArea, in order to force their recompilation, the problem remains. However deleting the class files for Staff and AbstractStaffHolder makes the error disappear and the system compiles properly.

I am using v4.11.1. I can't update any further because I am currently locked to play 2.4.4. With any luck this issue has already been fixed in more recent versions. If so, can someone point me to it so I can backport the fix to this version of the agent?

**Comment by jokester01au** [comment]
I've looked a bit closer at this and I have a theory as to what could be happening. 

    -- My project is mixed scala and java. 
    -- SBT is set to `compileOrder := Mixed`.
    -- The last time the issue occurred, I turned on verbose logging for SBT. It showed that both the MappedSuperclasses *and* the actual entity classes were scheduled to be recompiled.
    -- scalac executes before javac.

Given that deleting the MappedSuperclass `.class` files solves the problem, this suggests that these class files have been enhanced while the `.class` files for the entity have not. 

Actually, it doesn't matter whether or not the *Entity* class files have been enhanced. If I delete the *Entity* class files the problem remains.

In order to support circular dependencies in mixed compilation, scalac generates an AST for the relevant java classes. If there is a class file in the classpath it would appear that it uses the class file for AST generation. 

So if the superclass class file is enhanced and the entity class file either doesnt exist or is not enhanced, then the AST generation will strike this error.

The problem seems to me to be that the `EntityBean` interface is declared on the superclass but the implementation is left to the child Entity classes. They should probably both be done together -- either don't make a MappedSuperclass implement EntityBean, or add the EntityBean implementation to both the mapped superclass *and* the entity.

**Comment by jokester01au** [comment]
Hmm, looking more closely at the agent debug logging, I notice that it may be relevant that there are 2 levels of MappedSuperclass:

    ebean-enhance> cls: models/Staff  msg: ... skipping intercept <init> ... handled by super class... CONSTRUCTOR: owner:models/MyModel ()V

Its only these ones  ( SupplierStaff inherits Staff inherits MyModel)  that have the issue.

**Comment by rbygrave** [comment]
Are you still stuck on 4.x of the agent?

**Comment by rbygrave** [comment]
I'll close. Reopen as needed (ideally on a later release if possible).
