### ISSUE TITLE
How can I set logout for a transformer

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/ebean-agent#54]
There is a method on `Transformer`:

```java
public void setLogout(MessageOutput logout);
```

Question is how can I get the `Transformer` instance to call that API?

**Comment by rbygrave** [comment]
That depends on how the enhancement is performed.  So for an 'agent' the JVM creates the Transformer and for maven and gradle plugins etc the actual plugin creates the Transformer.

So the question is ... how are you doing the enhancement?

**Comment by greenlaw110** [comment]
I am using ebean-agent to do the enhancement. Here is the code:

https://github.com/actframework/act-ebean2/blob/master/src/main/java/act/db/ebean2/EbeanAgentLoader.java

**Comment by rbygrave** [comment]
Call the static get() method on Transformer.

```java
  public static Transformer get()  {
```
and then `setLogout(MessageOutput logout)`

Closing
