### ISSUE TITLE
Ebean-agent caused class been loaded twice

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/ebean-agent#56]
**Note** the issue is found on `ebean-agent-10.2.1`, it doesn't reproduce on `ebean-agent-10.1.7`

I have encountered a [weird issue](https://github.com/actframework/actframework/issues/218) when upgraded `ebean-agent` from `10.1.7` to `10.2.1`. 

After spending some time tracking the issue I found it is caused by double loading a class:

First time loading class `com.stevesoft.pat.ReplaceRule`

![image](https://cloud.githubusercontent.com/assets/216930/26544860/d7b1eae4-44a6-11e7-9eb3-bda38b2d0e7e.png)

Second time loading `com.stevesoft.pat.ReplaceRule`

![image](https://cloud.githubusercontent.com/assets/216930/26544998/62fe448a-44a7-11e7-821e-57e44807db60.png)

**Comment by rbygrave** [comment]
So yes, there is something we can try here with the 10.2.x agent. It will take a few days to get to it.

**Comment by greenlaw110** [comment]
Curious why ebean-agent tried to transform a class that is obvious not ebean relevant?

**Comment by rbygrave** [comment]
querybean enhancement (with java uses public fields and simulates 'properties' and that enhancement looks to modify callers/users of query beans).

If you look at https://github.com/ebean-orm/ebean-agent/issues/53

... you can specify a ebean.mf file and use that to effectively turn off querybean enhancement or limit its scope (packages it applies to).

**Comment by rbygrave** [comment]
query beans in native Kotlin use 'kotlin properties' and so in that case we only need to enhance the query beans themselves (and not enhance all callers/users of the query beans)

**Comment by rPraml** [comment]
@rbygrave this can be closed, It is adressed by #62

**Comment by rbygrave** [comment]
Closing.
