### ISSUE TITLE
Change entity enhancement back to COMPUTE and EXPAND FRAMES

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-agent#59]
So move back to use Compute and Expand Frames ASM options.  The downside here is the class loading requirement (for ASM to compute the frames etc) which can be difficult in some enhancement approaches (IDE plugins mostly).

**Comment by rPraml** [comment]
This Commit will fix the IDE-issues: 
https://github.com/FOCONIS/ebean-agent/commit/26ffbd4ffad063e0f607e8adb6f2bd44720d4816

**Comment by rbygrave** [comment]
Logged as https://github.com/ebean-orm/ebean-agent/issues/62
