### ISSUE TITLE
Loading of transactional class triggers ebean server creation (when it has a static initialiser method)

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean-agent#64]
When a transactional class is loaded (e.g. in spring dependency injection) the ebean server is created because the static initializer block is enhanced with the transactional code.

In the method io.ebean.enhance.transactional.ClassAdapterTransactional.visitMethod() the  &lt;init&gt; is skipped but the &lt;clinit&gt; isn't. 

Shouldn't the &lt;clinit&gt; method be skipped as well?

**Comment by rbygrave** [comment]
> Shouldn't the <clinit> method be skipped as well?

Yes it should.

**Comment by rnentjes** [comment]
This seems to be broken again:

	at io.ebeaninternal.api.HelpScopeTrans.server(HelpScopeTrans.java:26)
	at io.ebeaninternal.api.HelpScopeTrans.enter(HelpScopeTrans.java:15)
	at com.banktrade.clienttrade.common.base.dao.BaseDao.<clinit>(BaseDao.java:1)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

This triggers the creation of the ebean server while we would like to create the server ourselves (now it doesn't pick up the right settings and doesn't start).

See pull request #79 for a test which demonstrates this
