### ISSUE TITLE
@Transaction on class level causes clinit to be enhanced (transactional) - Regression introduced in 11.9.1

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean-agent#80]
I don't think it should do that (looks like a regression of #64). This is with ebean version 11.15.1 and intellij enhancement plugin 11.9.2

See pull request #79 for a demonstration of this.

**Comment by rbygrave** [comment]
This was a regression ... introduced by the change in #76 (Profile location enhancement)
