### ISSUE TITLE
QueryBean associations not enhanced [kotlin].

### ISSUE THREAD

**Issue by adrian5632** [ebean-orm/ebean-agent#81]
Hi! I am using the most recent versions of dependencies in my build.gradle:

```
kapt "io.ebean:kotlin-querybean-generator:11.1.2"
implementation "io.ebean:ebean:11.17.4"
implementation "io.ebean:ebean-querybean:11.3.1"
implementation "io.ebean:ebean-agent:11.11.1"
```
with io.ebean:ebean-gradle-plugin:11.10.1 plugin.

QueryBeans are nicely enhanced and queries with simple properties work just fine. However if I try to query related models, I'm getting the following error:
`UninitializedPropertyAccessException: lateinit property ticket has not been initialized`

And here's a minimised version of my models:
```
@MappedSuperclass
abstract class TicketBase : Model() { /* ... */ }

@Entity
@Table(name = "tbl_available_ticket")
class AvailableTicket(@Id var id: Long? = null) : TicketBase()

@Entity
@Table(name = "tbl_purchased_ticket")
class PurchasedTicket(
        @Id var id: Long? = null,
        // ...
        @ManyToOne var ticket: AvailableTicket?
) : TicketBase()
```

For now I have a nasty workaround for this:
```
val count = QPurchasedTicket().apply {
                ticket = QAssocAvailableTicket("ticket", this)
            }.ticket.id.equalTo(ticketId)
             .findCount()
```
but it would be nice to have it working out-of-the-box.

**Comment by rbygrave** [comment]
All working here with maven https://github.com/ebean-orm-examples/example-kotlin
... so maybe a gradle issue (but can't be a agent issue)

**Comment by rbygrave** [comment]
Updated the example at: https://github.com/ebean-orm-examples/example-gradle-kotlin
... and that is all working fine - no problem.

You should try and clone that example project ... run it ... and then compare.

**Comment by adrian5632** [comment]
OK, took me a lot of time but I finally figured out what was wrong. I did not have resources/ebean.mf file in my project - when I added that with `entity-packages` and `querybean-packages` specified everything seems to be working fine.

Just to be make sure, if I have my models in multiple packages, I should do something like:
```
entity-packages: my.package.x, my.package.y
querybean-packages: my.package.x, my.package.y
```
Correct?

Thanks!

**Comment by rbygrave** [comment]
> Correct?

Yes.  

Note that with Kotlin query beans we only need to enhance the query beans and not any calling code (unlike java query beans where we also need to enhance code that uses the query beans).

**Comment by rbygrave** [comment]
Closing as resolved.
